CREATE TABLE Products (
    ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    PRODUCT_PRICE DECIMAL(10, 2) NOT NULL,
    PRODUCT_ARTICLE VARCHAR(50) NOT NULL,
    PRODUCT_QUANTITY INT NOT NULL,
    DATE_CREATE DATE NOT NULL,
    HIDDEN BOOLEAN DEFAULT 0, 
    PRIMARY KEY (ID)
) ENGINE=INNODB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
